### ISSUE TITLE
Installation failed in windows 7 

### ISSUE THREAD

**Issue by FarshidShekari** [openai/retro#26] opened 2018-04-13 07:38 UTC
## Issue summary

after cloning the repo and then want to install it(this section https://github.com/openai/retro#install-from-source) I get  this error: 

> Obtaining file:///C:/Users/Farshid/gym-retro
> Requirement already satisfied: gym in c:\users\farshid\appdata\local\programs\py
> thon\python36\lib\site-packages (from gym-retro==0.5.4.dev9+gda18b9d)
> Requirement already satisfied: numpy>=1.10.4 in c:\users\farshid\appdata\local\p
> rograms\python\python36\lib\site-packages (from gym->gym-retro==0.5.4.dev9+gda18
> b9d)
> Requirement already satisfied: requests>=2.0 in c:\users\farshid\appdata\local\p
> rograms\python\python36\lib\site-packages (from gym->gym-retro==0.5.4.dev9+gda18
> b9d)
> Requirement already satisfied: six in c:\users\farshid\appdata\local\programs\py
> thon\python36\lib\site-packages (from gym->gym-retro==0.5.4.dev9+gda18b9d)
> Requirement already satisfied: pyglet>=1.2.0 in c:\users\farshid\appdata\local\p
> rograms\python\python36\lib\site-packages (from gym->gym-retro==0.5.4.dev9+gda18
> b9d)
> Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\farshid\appdata
> \local\programs\python\python36\lib\site-packages (from requests>=2.0->gym->gym-
> retro==0.5.4.dev9+gda18b9d)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\farshid\appdata
> \local\programs\python\python36\lib\site-packages (from requests>=2.0->gym->gym-
> retro==0.5.4.dev9+gda18b9d)
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\farshid\appdata\lo
> cal\programs\python\python36\lib\site-packages (from requests>=2.0->gym->gym-ret
> ro==0.5.4.dev9+gda18b9d)
> Requirement already satisfied: idna<2.7,>=2.5 in c:\users\farshid\appdata\local\
> programs\python\python36\lib\site-packages (from requests>=2.0->gym->gym-retro==
> 0.5.4.dev9+gda18b9d)
> Requirement already satisfied: future in c:\users\farshid\appdata\local\programs
> \python\python36\lib\site-packages (from pyglet>=1.2.0->gym->gym-retro==0.5.4.de
> v9+gda18b9d)
> Installing collected packages: gym-retro
>   Found existing installation: gym-retro 0.5.3
>     Uninstalling gym-retro-0.5.3:
>       Successfully uninstalled gym-retro-0.5.3
>   Running setup.py develop for gym-retro
>     Complete output from command c:\users\farshid\appdata\local\programs\python\
> python36\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Farshid
> \\gym-retro\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read()
> .replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop
> --no-deps:
>     running develop
>     running egg_info
>     writing gym_retro.egg-info\PKG-INFO
>     writing dependency_links to gym_retro.egg-info\dependency_links.txt
>     writing requirements to gym_retro.egg-info\requires.txt
>     writing top-level names to gym_retro.egg-info\top_level.txt
>     package init file 'data\__init__.py' not found (or not a regular file)
>     reading manifest template 'MANIFEST.in'
>     warning: no previously-included files matching '*.o' found anywhere in distr
> ibution
>     warning: no previously-included files matching '*.a' found anywhere in distr
> ibution
>     warning: no previously-included files matching '*.dylib' found anywhere in d
> istribution
>     warning: no previously-included files matching '*.so' found anywhere in dist
> ribution
>     warning: no previously-included files matching '*-version' found under direc
> tory 'retro\cores'
>     writing manifest file 'gym_retro.egg-info\SOURCES.txt'
>     running build_ext
>     error: [WinError 2] The system cannot find the file specified
> 
>     ----------------------------------------
>   Rolling back uninstall of gym-retro
> Command "c:\users\farshid\appdata\local\programs\python\python36\python.exe -c "
> import setuptools, tokenize;__file__='C:\\Users\\Farshid\\gym-retro\\setup.py';f
> =getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f
> .close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with e
> rror code 1 in C:\Users\Farshid\gym-retro\

## System information

- Windows 7
- Python 3.6.5
- gym-retro 0.5.4

**Comment by endrift** [comment] 2018-04-13 16:14
Is there more output? Try just installing the wheel.

**Comment by endrift** [comment] 2018-04-13 16:43
Possibly a duplicate of #13

**Comment by endrift** [comment] 2018-04-13 17:42
Is cmake installed and in PATH?

**Comment by fantom0** [comment] 2018-04-13 17:50
No hint to cmake in guideline

**Comment by endrift** [comment] 2018-04-13 17:52
it's at the top of the section you linked...

**Comment by fantom0** [comment] 2018-04-13 18:03
Now I get this error:
`Obtaining file:///C:/Users/Farshid/gym-retro
Requirement already satisfied: gym in c:\users\farshid\appdata\local\programs\py
thon\python36\lib\site-packages (from gym-retro==0.5.4.dev9+gda18b9d)
Requirement already satisfied: numpy>=1.10.4 in c:\users\farshid\appdata\local\p
rograms\python\python36\lib\site-packages (from gym->gym-retro==0.5.4.dev9+gda18
b9d)
Requirement already satisfied: requests>=2.0 in c:\users\farshid\appdata\local\p
rograms\python\python36\lib\site-packages (from gym->gym-retro==0.5.4.dev9+gda18
b9d)
Requirement already satisfied: six in c:\users\farshid\appdata\local\programs\py
thon\python36\lib\site-packages (from gym->gym-retro==0.5.4.dev9+gda18b9d)
Requirement already satisfied: pyglet>=1.2.0 in c:\users\farshid\appdata\local\p
rograms\python\python36\lib\site-packages (from gym->gym-retro==0.5.4.dev9+gda18
b9d)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\farshid\appdata
\local\programs\python\python36\lib\site-packages (from requests>=2.0->gym->gym-
retro==0.5.4.dev9+gda18b9d)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\farshid\appdata
\local\programs\python\python36\lib\site-packages (from requests>=2.0->gym->gym-
retro==0.5.4.dev9+gda18b9d)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\farshid\appdata\lo
cal\programs\python\python36\lib\site-packages (from requests>=2.0->gym->gym-ret
ro==0.5.4.dev9+gda18b9d)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\farshid\appdata\local\
programs\python\python36\lib\site-packages (from requests>=2.0->gym->gym-retro==
0.5.4.dev9+gda18b9d)
Requirement already satisfied: future in c:\users\farshid\appdata\local\programs
\python\python36\lib\site-packages (from pyglet>=1.2.0->gym->gym-retro==0.5.4.de
v9+gda18b9d)
Installing collected packages: gym-retro
  Found existing installation: gym-retro 0.5.3
    Uninstalling gym-retro-0.5.3:
      Successfully uninstalled gym-retro-0.5.3
  Running setup.py develop for gym-retro
    Complete output from command c:\users\farshid\appdata\local\programs\python\
python36\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Farshid
\\gym-retro\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read()
.replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop
--no-deps:
    running develop
    running egg_info
    writing gym_retro.egg-info\PKG-INFO
    writing dependency_links to gym_retro.egg-info\dependency_links.txt
    writing requirements to gym_retro.egg-info\requires.txt
    writing top-level names to gym_retro.egg-info\top_level.txt
    package init file 'data\__init__.py' not found (or not a regular file)
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.o' found anywhere in distr
ibution
    warning: no previously-included files matching '*.a' found anywhere in distr
ibution
    warning: no previously-included files matching '*.dylib' found anywhere in d
istribution
    warning: no previously-included files matching '*.so' found anywhere in dist
ribution
    warning: no previously-included files matching '*-version' found under direc
tory 'retro\cores'
    writing manifest file 'gym_retro.egg-info\SOURCES.txt'
    running build_ext
    -- The C compiler identification is unknown
    -- The CXX compiler identification is unknown
    CMake Error at CMakeLists.txt:23 (project):
      The CMAKE_C_COMPILER:

        cl

      is not a full path and was not found in the PATH.

      To use the NMake generator with Visual C++, cmake must be run from a shell

      that can use the compiler cl from the command line.  This environment is
      unable to invoke the cl compiler.  To fix this problem, run cmake from the

      Visual Studio Command Prompt (vcvarsall.bat).

      Tell CMake where to find the compiler by setting either the environment
      variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path t
o
      the compiler, or to the compiler name if it is in the PATH.


    CMake Error at CMakeLists.txt:23 (project):
      The CMAKE_CXX_COMPILER:

        cl

      is not a full path and was not found in the PATH.

      To use the NMake generator with Visual C++, cmake must be run from a shell

      that can use the compiler cl from the command line.  This environment is
      unable to invoke the cl compiler.  To fix this problem, run cmake from the

      Visual Studio Command Prompt (vcvarsall.bat).

      Tell CMake where to find the compiler by setting either the environment
      variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full pat
h
      to the compiler, or to the compiler name if it is in the PATH.


    -- Configuring incomplete, errors occurred!
    See also "C:/Users/Farshid/gym-retro/CMakeFiles/CMakeOutput.log".
    See also "C:/Users/Farshid/gym-retro/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Farshid\gym-retro\setup.py", line 67, in <module>
        use_scm_version=use_scm_version
      File "c:\users\farshid\appdata\local\programs\python\python36\lib\site-pac
kages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\farshid\appdata\local\programs\python\python36\lib\distutil
s\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\farshid\appdata\local\programs\python\python36\lib\distutil
s\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\farshid\appdata\local\programs\python\python36\lib\distutil
s\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\farshid\appdata\local\programs\python\python36\lib\site-pac
kages\setuptools\command\develop.py", line 36, in run
        self.install_for_development()
      File "c:\users\farshid\appdata\local\programs\python\python36\lib\site-pac
kages\setuptools\command\develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "c:\users\farshid\appdata\local\programs\python\python36\lib\distutil
s\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\farshid\appdata\local\programs\python\python36\lib\distutil
s\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Farshid\gym-retro\setup.py", line 39, in run
        subprocess.check_call(['cmake', '.', pyext_suffix, pylib_dir, python_exe
cutable])
      File "c:\users\farshid\appdata\local\programs\python\python36\lib\subproce
ss.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '.', '-DPYEXT_SUFFIX:STRIN
G=.cp36-win_amd64.pyd', '', '-DPYTHON_EXECUTABLE:STRING=c:\\users\\farshid\\appd
ata\\local\\programs\\python\\python36\\python.exe']' returned non-zero exit sta
tus 1.

    ----------------------------------------
  Rolling back uninstall of gym-retro
Command "c:\users\farshid\appdata\local\programs\python\python36\python.exe -c "
import setuptools, tokenize;__file__='C:\\Users\\Farshid\\gym-retro\\setup.py';f
=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f
.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with e
rror code 1 in C:\Users\Farshid\gym-retro\`

**Comment by endrift** [comment] 2018-04-13 18:05
Ok, this is an actual bug on my end. Do you have gcc installed? We don't currently have a tested workflow for building from source *on* Windows, as we use Docker to build for Windows on Linux.

**Comment by fantom0** [comment] 2018-04-13 18:08
No, not installd

**Comment by fantom0** [comment] 2018-04-13 18:08
No, not installd

**Comment by endrift** [comment] 2018-04-13 18:09
OK, then in the meantime I'd suggest you stick to the wheel. Building from source on Windows is currently unsupported, but I will try to figure out how to set it up.

**Comment by fantom0** [comment] 2018-04-13 18:11
I'm waiting for your solution.
tnx

**Comment by endrift** [comment] 2018-04-13 19:29
Ok, new instructions are in the repository now. Please `git pull`, remove the CMakeFiles folder and CMakeCache.txt, and follow the updated instructions. It worked on my end so let me know if there are any errors.

**Comment by fantom0** [comment] 2018-04-13 19:51
which one 1- in directory of gym-retro 2- installed with pip?

**Comment by endrift** [comment] 2018-04-13 20:01
In the directory of gym-retro, if they're there. Otherwise they may be in some temporary build directory you need to track down.

**Comment by fantom0** [comment] 2018-04-13 20:10
after delete it from gym-retro dir and want to run `pip3 install cmake` I can see that exist in another dir

**Comment by fantom0** [comment] 2018-04-14 13:50
I installed it, but when I write this `env = retro.make(game='SonicTheHedgehog-Genesis', state='GreenHillZone.Act1')` in cmd I get this error: 
```
Traceback (most recent call last):
  File "C:\Users\Farshid\gym-retro\retro\__init__.py", line 114, in make
    get_romfile_path(game)
  File "C:\Users\Farshid\gym-retro\retro\__init__.py", line 78, in get_romfile_p
ath
    raise FileNotFoundError("No romfiles found for game: %s" % game)
FileNotFoundError: No romfiles found for game: SonicTheHedgehog-Genesis

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Farshid\gym-retro\retro\__init__.py", line 119, in make
    raise FileNotFoundError('Game not found: %s. Did you make sure to import the
 ROM?' % game)
FileNotFoundError: Game not found: SonicTheHedgehog-Genesis. Did you make sure t
o import the ROM?
```

**Comment by endrift** [comment] 2018-04-14 18:16
Did you make sure to import the ROM?

**Comment by fantom0** [comment] 2018-04-14 18:33
I just use two command 
```
import retro
env = retro.make(game='SonicTheHedgehog-Genesis', state='GreenHillZone.Act1')
```
in python  IDLE. I encounter with above error.

**Comment by endrift** [comment] 2018-04-15 21:48
It sounds like you didn't import the ROM. Please follow the guidelines on https://contest.openai.com/details

**Comment by FarshidShekari** [comment] 2018-04-16 06:06
I write this code(same in page https://contest.openai.com/details => Now you can create a simple random agent in Python, random-agent.py:)
```
import retro

def main():
    env = retro.make(game='Airstriker-Genesis', state='Level1')
    obs = env.reset()
    while True:
        obs, rew, done, info = env.step(env.action_space.sample())
        env.render()
        if done:
            obs = env.reset()


if __name__ == '__main__':
    main()
```
I get this error:
```
Traceback (most recent call last):
  File "aa.py", line 1, in <module>
    import retro
  File "c:\users\farshid\gym-retro\retro\__init__.py", line 8, in <module>
    from retro._retro import Movie, RetroEmulator, core_path, data_path as _data
_path
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by endrift** [comment] 2018-04-16 16:26
Can you tell me the contents of c:\users\farshid\gym-retro\retro? Is there a _retro.pyd file?

**Comment by FarshidShekari** [comment] 2018-04-16 16:52
![image](https://user-images.githubusercontent.com/6597508/38823669-81026014-4196-11e8-8ed8-fd4bbc6c6287.png)

**Comment by endrift** [comment] 2018-04-17 23:04
Is your Python installation 64-bits?

**Comment by FarshidShekari** [comment] 2018-04-19 19:10
Yes
![image](https://user-images.githubusercontent.com/6597508/39012893-4a90db20-4405-11e8-941c-2aa0c3f696f2.png)

**Comment by nehz** [comment] 2018-04-27 07:32
Same issue with pip wheel binary installation on Windows 7, Python 3.5 64 bit:
"ImportError: DLL load failed: The specified procedure could not be found."

**Comment by endrift** [comment] 2018-05-30 17:38
I don't seem to be able to reproduce this with Python 3.6 (python.org version, not anaconda) on Windows 7. Did you make sure to add Python to your path?

**Comment by FarshidShekari** [comment] 2018-11-21 06:42
It's work. thanks

**Closed** 2018-11-21 19:08 UTC
