### ISSUE TITLE
playback_movie.py bk2 not working on windows

### ISSUE THREAD

**Issue by decoderkurt** [openai/retro#38] opened 2018-04-28 23:28 UTC
## Issue summary
is there any replacement for playback_movie.py for windows?

D:\project\results\bk2>python D:\project\gym-retro\scripts\playback_movie.py SonicTheHedgehog-Genesis-TEST.bk2
Traceback (most recent call last):
  File "D:\project\gym-retro\scripts\playback_movie.py", line 4, in <module>
    main()
  File "d:\project\gym-retro\retro\scripts\playback_movie.py", line 115, in main
    playback_movie(emulator, m, monitor_csv, movie.replace('.bk2', '.mp4'), args.viewer, delay)
  File "d:\project\gym-retro\retro\scripts\playback_movie.py", line 31, in playback_movie
    pass_fds=(vr, ar), stdout=stdout)
  File "C:\Users\kurt\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\kurt\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 968, in _execute_child
    assert not pass_fds, "pass_fds not supported on Windows."
AssertionError: pass_fds not supported on Windows.

## System information

- [Operating system] windows 10 pro
- [Python version] 3.6 64bit
- [Gym Retro version] 0.54

**Comment by endrift** [comment] 2018-04-29 15:44
Dupe of #20.

**Closed by endrift** 2018-04-29 15:44 UTC

**Comment by decoderkurt** [comment] 2018-04-29 23:38
I solved the problem by using docker ubuntu like this.

d:\docker run -v D:\project:/project myubuntu python3 /usr/project/gym-retro/scripts/playback_movie.py /project/results/bk2/AAAAAAAAAA.bk2
