### ISSUE TITLE
Agent not marking end of Episode

### ISSUE THREAD

**Issue by jamesrichter** [openai/retro#82] opened 2018-09-22 08:16 UTC
## Issue summary

I run Sonic the Hedgehog on my own script, but get this output:
```python3 ppo2_agent.py SonicTheHedgehog-Genesis
Logging to /tmp/openai-2018-09-21-17-34-20-554151
2018-09-21 17:34:33.719060: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
--------------------------------------
| approxkl           | 0.00081507413 |
| clipfrac           | 0.013509114   |
| eplenmean          | nan           |
| eprewmean          | nan           |
| explained_variance | -0.821        |
| fps                | 11            |
| nupdates           | 1             |
| policy_entropy     | 1.9451476     |
| policy_loss        | -0.000348951  |
| serial_timesteps   | 4096          |
| time_elapsed       | 342           |
| total_timesteps    | 4096          |
| value_loss         | 2.0339756     |
--------------------------------------
-------------------------------------
| approxkl           | 0.0026038953 |
| clipfrac           | 0.18782552   |
| eplenmean          | nan          |
| eprewmean          | nan          |
| explained_variance | 0.264        |
| fps                | 12           |
| nupdates           | 2            |
| policy_entropy     | 1.9411093    |
| policy_loss        | -0.006173628 |
| serial_timesteps   | 8192         |
| time_elapsed       | 683          |
| total_timesteps    | 8192         |
| value_loss         | 0.0015558713 |
-------------------------------------
...
--------------------------------------
| approxkl           | 0.002821725   |
| clipfrac           | 0.12223307    |
| eplenmean          | nan           |
| eprewmean          | nan           |
| explained_variance | 0.452         |
| fps                | 11            |
| nupdates           | 49            |
| policy_entropy     | 1.3499503     |
| policy_loss        | -0.0018281041 |
| serial_timesteps   | 200704        |
| time_elapsed       | 1.92e+04      |
| total_timesteps    | 200704        |
| value_loss         | 0.0002322265  |
--------------------------------------
```
I've looked at the rendered environment and Sonic does in fact die.  This should trigger a new episode?  Also, when I run Atari on a different script serial_timesteps and total_timesteps are different.  It could be the script I am using.

## System information

- Ubuntu
- Python 3
- Retro 0.6.0

**Comment by simoninithomas** [comment] 2018-09-22 13:46
Hi @jamesrichter ,

I don't understand your problem you say "This should trigger a new episode?" **it depends only on how you've implemented the environment.**

If you use something like DummyVecEnv from openai baselines it handles directly this.

If you think the problem is because `eplenmean  and eprewmean = nan`, it's normal, **Sonic does not have in his info this two elements.**

**Comment by christopherhesse** [comment] 2018-11-21 02:02
@jamesrichter New episodes must be triggered by the user, as the gym docs state: https://github.com/openai/gym/blob/master/gym/core.py#L47 the user must call reset() on the environment after done is true.  As @simoninithomas pointed out, this is automatic if it's wrapped by a VecEnv, but otherwise it is up to the training code to do this.

@simoninithomas The missing eplenmean and eprewmean are normally provided, oddly enough, by a Monitor wrapper: https://github.com/openai/baselines/blob/master/baselines/bench/monitor.py#L12

I will close this issue if there are no other questions about this particular thing.

**Comment by christopherhesse** [comment] 2018-12-01 01:10
Looks like no other questions, closing.

**Closed by christopherhesse** 2018-12-01 01:10 UTC
